import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AppShellDemo from "../components/AppShell";
import AppShellGlobal from "../components/AppShellGlobal";

// @ts-ignore
const Home: NextPage = ({currentTheme, setDarkMode}: { currentTheme: any, setDarkMode: any }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>CAMS</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logo/logo-black.svg"/>
            </Head>
            <AppShellGlobal currentTheme={currentTheme} setDarkMode={setDarkMode}></AppShellGlobal>
        </div>
    )
}

export default Home
